name: Check CS

on:
    push:
    pull_request_target:
        types: [opened, synchronize]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Check code style
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: none
                    php-version: "7.4"
                    tools: cs2pr

            -   name: Install dependencies with composer
                run: composer install

            -   if: ${{ github.base_ref == '' }}
                run: composer cscheck

            -   name: Run code style check with code sniffer
                if: ${{ github.base_ref != '' }}
                run: vendor/bin/phpcs --standard=Solido src/ --report=checkstyle | cs2pr
