name: PHPStan

on:
    push:
    pull_request_target:
        types: [opened, synchronize]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Static analysis
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: none
                    php-version: "8.2"
                    tools: cs2pr

            -   name: Install dependencies with composer
                run: composer install

            -   if: ${{ github.base_ref == '' }}
                run: composer phpstan

            -   name: Run a static analysis with phpstan/phpstan
                if: ${{ github.base_ref != '' }}
                run: composer phpstan -- --error-format=checkstyle | cs2pr
