name: Tests
on:
    push:
    pull_request_target:
        types: [opened, synchronize]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                composer_flags:
                    - ''

                php_version:
                    - '8.1'
                    - '8.2'
                    - '8.3'
                    - '8.4'

                dbal_version:
                    - 3.0
                    - 4.0

        name: PHP ${{ matrix.php_version }} - DBAL ${{ matrix.dbal_version }}
        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP with pecl extension
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php_version }}
                  tools: pecl
                  extensions: :opcache, mongodb

            - run: composer remove --no-update --dev roave/security-advisories solido/php-coding-standards
            - run: composer require --no-update doctrine/dbal:^${{ matrix.dbal_version }}
            - run: composer update --with-all-dependencies ${{ matrix.composer_flags }}

            - run: vendor/bin/phpunit --coverage-clover coverage.xml
              env:
                  XDEBUG_MODE: coverage

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
                  file: ./coverage.xml
